process.env.NODE_ENV = 'test';
process.env.CORS_ORIGINS = '*';
process.env.RATE_LIMIT_MAX = '1000';
process.env.PUBLIC_BASE_URL = 'http://127.0.0.1:3299';
process.env.USERS_FILE = new URL('../../server/test/fixtures/users.json', import.meta.url).pathname;
process.env.VIDEOS_FILE = new URL('../../server/test/fixtures/videos.json', import.meta.url).pathname;
process.env.SKAZ_ENABLED = '0';
process.env.FILMIX_ENABLED = '0';
process.env.REZKA_ENABLED = '0';
process.env.KODIK_ENABLED = '0';
process.env.ALLOHA_ENABLED = '0';
process.env.COLLAPS_ENABLED = '0';
process.env.HDVB_ENABLED = '0';
process.env.KINOTOCHKA_ENABLED = '0';
const { server } = await import('../../server/src/index.js');
await new Promise((r) => server.listen(3299, '127.0.0.1', r));
const r = await fetch('http://127.0.0.1:3299/api/lampa/sources/card?token=unit-test-token&id=13&serial=0&source=tmdb&kinopoisk_id=13');
const body = await r.json();
for (const s of body.sources) console.log(`${String(s.show)}\t${s.id}`);
const bad = body.sources.filter((s) => s.id !== 'cdnvideohub' && s.show !== true);
console.log('BAD non-cdnvideohub:', JSON.stringify(bad));
await new Promise((r) => server.close(r));
